apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-pathrouting-1
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: wldomain.org
    http:
      paths:
      - path: /testwebapp
        backend:
          serviceName: domain1-cluster-cluster-1
          servicePort: 8001
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-pathrouting-2
  namespace: test1
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: wldomain.org
    http:
      paths:
      - path: /testwebapp
        backend:
          serviceName: domain2-cluster-cluster-1
          servicePort: 8001
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-pathrouting-3
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: traefik.example.com
    http:
      paths:
      - path: /dashboard
        backend:
          serviceName: traefik-operator-dashboard
          servicePort: 80


